name: ElementalSkills
main: com.comze_instancelabs.elementalskills.Main
version: 1.0
author: instancelabs
softdepend: [Vault]
commands:
   element:
      description: Main command
      usage: /element [action]
      aliases: [elem]
   skill:
      description: Main command
      usage: /skill [action]
      aliases: [skills, sk]
   highscore:
      description: Main command
      usage: /highscore [action]
      aliases: [hi]
